# Generated by Django 5.1.4 on 2025-01-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_alter_budget_category_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='exceeded_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
